# Auto-release on commit to master, beta pre-release on commit to dev
name: AutoRelease

on:
  push:
    branches:
      - master
      - dev

jobs:
  release:
    name: Release (master)
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CupOfTea696/gh-action-auto-release@v1.0.2
        with:
          title: 'Release: $version'
          tag: 'v$semver'
          draft: false
          regex: '/^Release: #{semver}$/i'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  beta:
    name: Beta Pre-release (dev)
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CupOfTea696/gh-action-auto-release@v1.0.2
        with:
          title: 'Beta: $version'
          tag: 'v$semver'
          draft: false
          regex: '/^Beta: #{semver}$/i'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
